export const keywords = [
	"UAF CGPA Calculator",
	"UAF",
	"CGPA Calculator",
	"GPA Calculator UAF",
	"UAF GPA Calculator",
	"UAF CGPA System",
	"University of Agriculture Faisalabad",
	"GPA Calculator",
	"UAF GPA System",
	"Pakistan University Calculator",
	"Student CGPA Tool",
	"Academic Calculator UAF",
	"Semester GPA Calculator",
	"percentage converter",
	"online CGPA calculator",
	"convert CGPA to percentage",
	"UAF GPA converter",
	"GPA calculation tool",
	"academic GPA calculator",
	"UAF Result Calculator",
	"UAF GPA Conversion",
	"UAF GPA to Percentage",
	"UAF CGPA to Percentage",
	"UAF GPA Calculation",
	"UAF CGPA Calculation",
	"UAF GPA Conversion Tool",
	"UAF CGPA Conversion Tool",
	"UAF GPA to Percentage Converter",
	"UAF CGPA to Percentage Converter",
	"UAF CGPA Calculator Online",
	"UAF GPA Calculator Online",
	"UAF CGPA Calculator 2022",
	"UAF GPA Calculator 2022",
	"UAF CGPA Calculator 2023",
	"UAF GPA Calculator 2023",
	"UAF CGPA Calculator 2024",
	"UAF GPA Calculator 2024",
	"UAF CGPA Calculator 2025",
	"UAF GPA Calculator 2025",

]	